//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LTCSDL_pro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        
        public KhachHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }

        [Display(Name = "Mã khách hàng")]//Display thay đổi thuộc tính hiển thị.
        public int MaKH { get; set; }

        [Display(Name = "Họ và Tên")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public string HoTen { get; set; }

        [Display(Name = "Tài khoản")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public string TaiKhoan { get; set; }

        [Display(Name = "Mật khẩu")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public string MatKhau { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^[a-zA-Z0-9.]+@gmail\.com$", ErrorMessage = "Invalid email format")]
        public string Email { get; set; }

        [Display(Name = "Địa chỉ")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public string DiaChi { get; set; }

        [Display(Name = "Điện thoại")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public string DienThoai { get; set; }

        [Display(Name = "Giới tính")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này.")]//Kiểm tra dữ liệu rỗng
        public string GioiTinh { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]//Định dạng ngày
        [Display(Name = "Ngày sinh")]//Display thay đổi thuộc tính hiển thị.
        [Required(ErrorMessage = "Vui lòng nhập liệu cho trường này!")]//Kiểm tra dữ liệu rỗng
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
